###
GET http://localhost:3000/api/users/consult-users

###
GET http://localhost:3000/api/users/get-user/1



###
POST http://localhost:3000/api/users/save-user
Content-Type: application/json

{
    "names": "carlos urrego alzate",
    "email": "carlos@gmail.com",
    "password": "carlos12"
}

###
PUT http://localhost:3000/api/users/update-user
Content-Type: application/json

{
    "id": 2,
    "names": "carlos urrego alzate",
    "email": "carlos@gmail.com",
    "password": "carlos12"
}

###
DELETE http://localhost:3000/api/users/delete-user/6

